In [3]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data tye
import numpy as np
arr1=np.arange(5)
arr1.dtype

dtype('int32')

In [4]:
#2. Given a NumPy array 'arr', check if its data type is float64
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype==np.float64:
    print('true') 
else:
    print('false')

true


In [5]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr=np.array([2, 6],dtype = np.complex128)
arr
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.array([1,2,3,4,5],dtype=np.int32)
arr=np.array(arr,dtype=np.float32)
arr
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr=np.array([1,2,3,4,5],dtype=np.float64)
arr=np.array([1,2,3,4,5],dtype=np.float32)
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
# type.
def array_attribute(arr):
    if not isinstance(arr,np.ndarray):
        raise ValueError("Input must be a numpy array.")
    shape=arr.shape
    size=arr.size
    datatype=arr.dtype
    return [shape, size ,datatype]
arr=np.array([1,2,3,4,5],dtype=np.float64)
print(array_attribute(arr))
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
    if not isinstance(arr, np.ndarray):
        return ValueError("Input must be a numpy array.") 
    return arr.ndim
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
print(array_dimension(arr))
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
# size in bytes.
def item_size_info(arr):
    if not isinstance(arr,np.ndarray):
        return ValueError("Input must ba a numpy array")
    return arr.itemsize
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float32)
print(item_size_info(arr))

# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
arr = np.array([1.5, 2.6, 3.7])
def array_strides(arr):
    if not isinstance(arr, np.ndarray):
        return ValueError("Input must be a numpy array.")
    return arr.strides
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
# and strides of the array.
def shape_stride_relationship(arr):
    if not isinstance(arr,np.ndarray):
        return ValueError("Input must be a numpy array")
    shape=arr.size
    stride=arr.strides
    return {"shape ":shape, 
            "stride ":stride}
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float32)
print(shape_stride_relationship(arr))

# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements.
# def create_zeros_array():
#     arr=input("Enter the n number of elements:")
#     return np.array(arr)
# if __name__ == "__main__":
#     print(create_zeros_array())
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.
def create_one_matrix(rows,cols):
    return np.ones((rows,cols))
if __name__=='__main__':
    print(create_one_matrix(4,5))
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
# `step`.
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
if __name__=='__main__':
    print(generate_range_array(8,100,2))
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
# (inclusive).
def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)
if __name__=='__main__':
    print( generate_linear_space(8,100,5))    
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye`.
# def create_identity_matrix():
#     a=int(input("Enter the integers:"))
#     return np.eye(a,dtype=np.int32)
# if __name__=='__main__':
#     print(create_identity_matrix())        
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(lis):
    if not isinstance(lis,list):
        ValueError("Input must be list")
    print("THe original data type is ",type(lis))
    return np.array(lis)
lis=[1,2,34,5,67,8.9]
a=list_to_array(lis)
type(a)
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
# same data.
a=[1,2,3,4,5,6,7,8]
a=np.array(a)
b = a.view().reshape(2,4)
b[0,1]=5
print(a)
print(b)

# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatn(arr1,arr2):
    if not isinstance(arr1,np.ndarray):
        return ValueError("Input must be numpy array")
    if not isinstance(arr2,np.ndarray):
        return ValueError("Input must be numpy array")
    return np.concatenate((arr1,arr2),axis=0) 
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(concatn(arr1,arr2))
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
# concatenate`.
def concatn(arr1,arr2):
    if not isinstance(arr1,np.ndarray):
        ValueError("Input must be numpy array")
    if not isinstance(arr2,np.ndarray):
        ValueError("Input must be numpy array")
    return np.concatenate((arr1,arr2),axis=0) 
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(concatn(arr1,arr2))

# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.
import numpy as np

def vertical_stack(arrays):
   
    # Check if the input is a list
    if not isinstance(arrays, list):
        raise ValueError("Input must be a list of NumPy arrays.")
    
    # Use numpy.vstack to stack the arrays
    stacked_array = np.vstack(arrays)
    
    return stacked_array

# Example usage
if __name__ == "__main__":
    # Create some sample arrays
    array1 = np.array([[1, 2, 3]])
    array2 = np.array([[4, 5, 6]])
    array3 = np.array([[7, 8, 9]])

    # Stack the arrays vertically
    result = vertical_stack([array1, array2, array3])
    
    print("Stacked Array:")
    print(result)


# 21. Write a Python function using NumPy to create an array of integers
#within a specified range (inclusive) with a given step size.
import numpy as np
def NumArr(st, end , step):
    end=end+1
    arr=np.arange(st,end,step)
    return arr
if __name__ =='__main__':
    print(NumArr(1,9,4))
    

# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
# (inclusive).
import numpy as np
def NumArr2(num):
    arr=np.linspace(0,1,10)
    return arr
if __name__=='__main__':
    print(NumArr2(10))
    
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
# 1000 (inclusive).
import numpy as np
def NumArr3(num):
    arr=np.logspace(0,3,5)
    return arr
if __name__=='__main__':
    print(NumArr3(5))
    

# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.
import pandas as pd
import numpy as np
arr1=np.random.randint(-101,101,size=(5,3))
df = pd.DataFrame(arr1, index=None)
df





[(5,), 5, dtype('float64')]
2
4
{'shape ': 10, 'stride ': (20, 4)}
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54
 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
[  8.  31.  54.  77. 100.]
THe original data type is  <class 'list'>
[1 5 3 4 5 6 7 8]
[[1 5 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
Stacked Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


0   1   2
0  90 -55  61
1  91 -65 -96
2 -16  72  45
3 -32 -93 -56
4  22  69 -88

In [6]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame.*/
import pandas as pd
import numpy as np

def replace_negatives_with_zero(df, column_name):
    # Replace negative values with 0 using NumPy's where function
    df[column_name] = np.where( df[column_name],df[column_name] < 0, 0)
    return df

# Example usage:
if __name__ == '__main__':
    data = {'A': [1, -2, 3, -4, 5], 'B': [-10, 20, -30, 40, -50]}
    df = pd.DataFrame(data)
    print("Before replacing negatives:")
    print(df)
    
    # Replace negatives in column 'A'
    updated_df = replace_negatives_with_zero(df, 'A')
    
    print("\nAfter replacing negatives in column 'A':")
    print(updated_df)


Before replacing negatives:
   A   B
0  1 -10
1 -2  20
2  3 -30
3 -4  40
4  5 -50

After replacing negatives in column 'A':
   A   B
0  0 -10
1  1  20
2  0 -30
3  1  40
4  0 -50


In [7]:
df<0

A      B
0  False   True
1  False  False
2  False   True
3  False  False
4  False   True

In [8]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[2]

# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr_2d[1][2]




# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
cond = arr>5 
arr1 = arr[cond]
arr1

# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=arr[2:6]
arr

# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.


arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr=arr_2d[:2,1:3]
arr

array([[2, 3],
       [5, 6]])

In [9]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another array.
# import numpy as np

# def extract_elements(array_2d, indices):

#     # Ensure the indices are in the right shape
#     indices = np.array(indices).flatten()
    
#     # Get the shape of the array
#     num_rows, num_cols = array_2d.shape
    
#     # Calculate the row and column indices
#     row_indices = indices // num_cols
#     col_indices = indices % num_cols
    
#     # Extract the elements using advanced indexing
#     extracted_elements = array_2d[row_indices, col_indices]
    
#     return extracted_elements

# # Example usage
# array_2d = np.array([[1, 2, 3],
#                      [4, 5, 6],
#                      [7, 8, 9]])

# indices = np.array([0, 1, 4, 7])  # Extracts elements at positions (0,0), (0,1), (1,1), (2,1)
# extracted = extract_elements(array_2d, indices)
# print(extracted)

# # 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
# # boolean indexing.
# arr=np.random.randint(0, 100, size=15)
# print(arr)
# n = int(input("Enter The Threshold Value:"))
# mask = arr>n
# arr=arr[mask]
# print(arr)

# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
# separate arrays for each dimension.

def extractedElement(arr, arr1, arr2,arr3):
    arr1=np.array(arr1).flatten()
    arr2=np.array(arr2).flatten()
    arr3=np.array(arr3).flatten()
    extracted= arr[arr1,arr2,arr3]
    return extracted
arr=np.random.randint(0,100,size=(6,6,6))
print(arr)
arr1=[1,3,5,2,4,5]
arr2=[1,4,2,3,5,0]
arr3=[3,2,1,4,5,0]
Element = extractedElement(arr,arr1,arr2,arr3)
print(Element)

# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing. 
arr1=np.random.randint(1,100,15)
print(arr1)
mask1=arr1>50
mask2=arr1<80
mask3=mask1 & mask2 
masked_array=arr1[mask3]
print(masked_array)
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays.
# def extract_elements(array_2d, indices):

#     # Ensure the indices are in the right shape
#     indices = np.array(indices).flatten()
    
#     # Get the shape of the array
#     num_rows, num_cols = array_2d.shape
    
#     # Calculate the row and column indices
#     row_indices = indices // num_cols
#     col_indices = indices % num_cols
    
#     # Extract the elements using advanced indexing
#     extracted_elements = array_2d[row_indices, col_indices]
    
#     return extracted_elements

# # Example usage
# array_2d = np.array([[1, 2, 3],
#                      [4, 5, 6],
#                      [7, 8, 9]])

# indices = np.array([0, 1, 4, 7])  # Extracts elements at positions (0,0), (0,1), (1,1), (2,1)
# extracted = extract_elements(array_2d, indices)
# print(extracted)

# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

# arr1=np.random.randint(1,100,size=(3,3))
# print(arr1)
# arr1=arr1+5
# print(arr1)


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.
# arr1=np.random.randint(1,10,size=(1,3))
# print(arr1)
# arr2=np.random.randint(1,10,size=(3,3))
# print(arr2)
# arr2=arr2*arr1
# arr2

# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting.
# arr1=np.random.randint(1,10,size=(1,4))
# print(arr1)
# arr1=arr1.T
# arr2=np.random.randint(1,10,size=(4,3))
# print(arr2)
# arr2=arr2+arr1
# arr2


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
# broadcasting.
arr1=np.random.randint(1,10,size=(3,1))
print(arr1)

arr2=np.random.randint(1,10,size=(1,3))
print(arr2)
arr2=arr2+arr1
arr2




# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.

import numpy as np

# Given arrays
arr1 = np.random.randint(1, 10, size=(2, 3))  # shape (2, 3)
arr2 = np.random.randint(1, 10, size=(2, 2))  # shape (2, 2)

# To multiply arr1 and arr2 using broadcasting, we need to reshape arr2.
# We reshape arr2 to (2, 1) to make it compatible for broadcasting
arr2_reshaped = arr2[:, 0:1]  # Reshape arr2 to (2, 1)

# Now multiply arr1 and arr2_reshaped using broadcasting
result = arr1 * arr2_reshaped

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("arr2 reshaped:\n", arr2_reshaped)
print("Result of broadcasting multiplication:\n", result)



[[[ 1  2 73 51 94 73]
  [14 90 73 47  0 16]
  [50 29 40 98 24 74]
  [59 25 49  3 75 61]
  [55 60 99 55 88 15]
  [43 43 19  0 94 54]]

 [[93 80 85  4 24 44]
  [27 97 70  3 81 93]
  [34 12 70 91  4 87]
  [34 40 97 60 81  1]
  [92 98 66 25 29  1]
  [20 94 89 54 91  2]]

 [[32 22 33 56 27 68]
  [79 88 42 26 55 63]
  [54 19 31 69 31 25]
  [57 47 86 10 84 23]
  [76 58 71 23 10 37]
  [79 32 37 93 43 55]]

 [[26 36 95 16 87 62]
  [99 25 46 42 31 63]
  [ 6 60 85 60 61  5]
  [48 86 47 54 92 15]
  [ 0 65 97  9 12 73]
  [ 9 47 48 78 26 60]]

 [[23 64 41 77 36 59]
  [29 26 10  3 93 95]
  [52 43 77 84 96  5]
  [35 10 20 31 67  4]
  [57 33  5 77 96 82]
  [ 5 47 65  8 21 71]]

 [[66  3  9 17  1 23]
  [65 84 88  1 17  6]
  [38  9 50 89 52 61]
  [42  9 86 57 91  8]
  [ 2 11 84 78 57 80]
  [56 49 31 42 41 10]]]
[ 3 97  9 84 71 66]
[12 81 34 43 27 22 95 65 89 45 18 24 43 72 67]
[65 72 67]
[[1]
 [8]
 [4]]
[[4 3 9]]
arr1:
 [[2 1 2]
 [7 4 9]]
arr2:
 [[8 1]
 [1 5]]
arr2 reshaped:
 [[8]
 [1]]
Result of broadca

[ 1  2 10  3  4  5]
[ 1  2 10  3 11  4  5]
[ 1 10  3 11  4  5]
[ 1 10  3  4  5]


In [38]:
# 41. Calculate column-wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr=arr.T
def avg(cols):
    return cols.mean()
for i , cols in enumerate(arr):
    result = avg(cols)
    print(f"Result for column {i+1}:{result}")
    


# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i, row in enumerate(arr):
    result = row.min()
    print(f"Min of {i+1} row is {result}")
    



# 43. For the given array, find indices of maximum value in each column.
# Using ndenumerate and ndindex: NumPy provides np.ndenumerate and np.ndindex functions, which are 
# helpful for iterating over array indices.
arr = np.array([[1, 2, 3], [4, 5, 6]])
for index , value in np.ndenumerate(arr):
    print(f"Index:{index},Value:{value}")
for index in np.ndindex(arr.shape):
    print(f"Index:{index}, Value:{arr[index]}")


# 44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i, row in enumerate(arr):
    value= row.sum()
    print(f"{i}th row sum:{value}")

# 45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
for i, row in enumerate(arr):
    all_even= np.all(row % 2==0)
    print(f"Elements in  {i+1}th Row is positive :{all_even}")


# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows 
#and `n` columns. Return the # reshaped matrix.
m=int(input("Enter m:"))
n=int(input("Enter n:"))
original_array = np.array([1, 2, 3, 4, 5, 6])
np.reshape(a,(m,n))

# 47. Create a function that takes a matrix as input and returns the flattened array.
def flatarr(arr):
    if  not isinstance (arr,np.ndarray):
        return ValueError('The object is not an array object')
    return arr.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(flatarr(input_matrix))

# 48. Write a function that concatenates two given arrays along a specified axis.
def concatarr(arr1,arr2):
    concatenated_array = np.concatenate((arr1, arr2))
    print(concatenated_array)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatarr(array1,array2)

# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.


original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arr = np.split(original_array, [1],axis =1)
print(split_arr)
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

def insertElement(element,arr,index):
    inserted_arr = np.insert(arr,index, element)
    print(inserted_arr)
    return inserted_arr
    
def deleteElement(arr,index):
    deleted_arr = np.delete(arr, index)
    print(deleted_arr)
    return deleted_arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert=[2,4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

original_array =insertElement(10,original_array,2) 

original_array =insertElement(11,original_array,4) 
original_array =deleteElement(original_array,1) 
original_array =deleteElement(original_array,3) 






# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.
np.arange()


# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
np.exp()

# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])



# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# 59. Write a function that concatenates strings in a NumPy array element-wise.

# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])

# 60. Write a function that finds the length of the longest string in a NumPy array.

# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])



# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
# dataset.


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function.


# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles.


# 66. Create a NumPy array of integers and find the index of a specific element.


# 67. Generate a random NumPy array and sort it in ascending order.


# 68. Filter elements >20 in the given NumPy array.

# arr = np.array([12, 25, 6, 42, 8, 30])


# 69. Filter elements which are divisible by 3 from a given NumPy array.
# arr = np.array([1, 5, 8, 12, 15])


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

# arr = np.array([1, 2, 3])

# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
F
# 73. For the given NumPy array, swap its byte order without modifying the original array using
# `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using
# `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
# attribute `byteorder`.
# arr = np.array([1, 2, 3], dtype=np.int32)


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.


# 83. Create a matrix `E` and find its transpose.


# 84. Generate a square matrix `F` and compute its determinant.


# 85. Create a square matrix `G` and find its inverse.






Result for column 1:2.5
Result for column 2:3.5
Result for column 3:4.5
Min of 1 row is 1
Min of 2 row is 4
Index:(0, 0),Value:1
Index:(0, 1),Value:2
Index:(0, 2),Value:3
Index:(1, 0),Value:4
Index:(1, 1),Value:5
Index:(1, 2),Value:6
Index:(0, 0), Value:1
Index:(0, 1), Value:2
Index:(0, 2), Value:3
Index:(1, 0), Value:4
Index:(1, 1), Value:5
Index:(1, 2), Value:6
0th row sum:6
1th row sum:15
Elements in  1th Row is positive :True
Elements in  2th Row is positive :False


Enter m: 4
Enter n: 2


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1],
       [4],
       [7]]), array([[2, 3],
       [5, 6],
       [8, 9]])]


NameError: name 'indices_to_insert' is not defined

[[1 4]
 [2 5]
 [3 6]]
[1 4]
Result for Row 1:2.5
[2 5]
Result for Row 2:3.5
[3 6]
Result for Row 3:4.5
