In [322]:
import numpy as np


In [323]:
np.__version__

'2.1.1'

In [324]:
lis = [1,2,3,'pwskills',(3+5j)]

In [325]:
type(lis)

list

In [326]:
#Numpy stores the data in an array 
#An array is a container and to store th data of same data type

In [327]:
#numpy is array based which make it fast  beacuse of the contigious memory allocation
#mathematcial computation

In [328]:
l= [1,2,3,4,5]

In [329]:
arr= np.array(l)   #{most fundamental element of computation}

In [330]:
arr


array([1, 2, 3, 4, 5])

In [331]:
l= [1,2,3,4,5.1]

In [332]:
l= np.array(l)

In [333]:
l

array([1. , 2. , 3. , 4. , 5.1])

In [334]:
l= [1,2,3,4,5.1,"Nitish"]
arr= np.array(l)

In [335]:
arr

array(['1', '2', '3', '4', '5.1', 'Nitish'], dtype='<U32')

In [336]:
type(arr)

numpy.ndarray

In [337]:
arr.ndim

1

In [338]:
arr1= np.array([[1,2,3],[4,5,6]])

In [339]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [340]:
arr1.ndim

2

In [341]:
#representaion of data in vector form is know as matrix 

In [342]:
#the inverse of matrix is not easy to find out that is why we got matix array(specialised numpy array)

In [343]:
mat = np.matrix([1,2,3,4])

In [344]:
type(mat)

numpy.matrix

In [345]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
#more way to convert array
#np.asarray(convert to array from any type whether it is subtype of array(matrix) ) ,np.array(convert to array similar similar to asarray ), np.asanyarray(convert to array but it should not be any subtype of array)
## a.copy() , a.array()

In [ ]:
l=[1,2,3,4,5]

In [ ]:
arr = np.asarray(l)

In [ ]:
type(arr)

In [ ]:
mat

In [ ]:
 m= np.matrix([1,2,3,4])

In [ ]:
np.asanyarray(m)

In [ ]:
arr1 = np.matrix([[1, 2], [3, 4]])
arr2 = np.asanyarray(arr1)  # Preserves the matrix type
type(arr2)

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])  # Creates a new array
arr2 = np.array(arr1)        # Creates a copy of arr1
arr1[0]=5
arr2

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.asarray(arr1)  # Does not copy arr1, reuses the original array
arr1[0]=5
arr2

In [ ]:
#multiple ways to create array   through function 

In [ ]:
arr1=np.fromfunction(lambda i, j: i==j, (3,3))   #construct an array by executing a function over each coordinate

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

#arrray with the help of iterables 

In [ ]:
#making of iterables 
iterable =(i for i in range(5))


In [ ]:
np.fromiter(iterable, int) # create one dimensional array from iterable object 

In [ ]:
np.fromstring('22 23 24',sep=" ") #works well from numerical data 

In [ ]:
    #the string character split function for  converting to array 

In [ ]:
str = 'Ajay, Bijay,Sanjay '
string1= str.split(',')

In [ ]:
np.array(string1)

In [ ]:
#in numpy there is the function like range that is used to make array 
#it is very much similar to the range function in pyhton 

In [ ]:
#other methods of numpy >> to generate sequennce of nos 
np.arange(1,10,0.1)

In [ ]:
np.linspace(1,5,10) #Return evenly spaced numbers over a specified interval.
#give me 10 numbers between 1 and 5 evenly spaced 

In [ ]:
np.logspace(1,5,10)

In [ ]:
np.logspace(1,5,10,base=2

In [ ]:
#Lecture 2 


In [ ]:
import numpy as np

In [ ]:
a=np.zeros(5) #Return a new array shape and type,filled with zeros.

In [ ]:
a.ndim
a


In [ ]:
 b= np.zeros((3,4))

In [ ]:
b.ndim
b

In [ ]:
np.ones((3,4))

In [ ]:
#np.twos((5,4)) this doesn't exist only zero's and one's 

In [ ]:
np.array([[2,2,2],[2,2,2]])

In [ ]:
arr=np.zeros((3,4))

In [ ]:
arr


In [ ]:
arr.ndim

In [ ]:
#3 dimensional array
np.zeros(1)

In [ ]:
np.zeros((2,3))

In [ ]:
arr = np.zeros((3,4))
arr.ndim

In [ ]:
arr = np.zeros((1,3,4))

In [ ]:
arr

In [ ]:
arr.ndim

In [ ]:
arr= np.zeros((1,1,3,4))
arr

In [ ]:
arr.ndim

In [ ]:
arr= np.zeros((1,1,1,3,4))
arr

In [ ]:
arr.ndim

In [ ]:
arr

In [ ]:
arr= np.ones((3,4))

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr

In [ ]:
arr + 5

In [ ]:
arr=arr * 5

In [ ]:
arr -1

In [ ]:
np.eye(3)

In [ ]:
np.eye(3, dtype =int)

In [ ]:
np.empty((3,4)) #Return a new array of given shape and type , without initializing entries 

In [ ]:
#optional >> random module 

import random
random.choice((1,2,3,4,5))



In [ ]:
random.randrange(1,10)

In [ ]:
random.choice('Ajay')

In [ ]:
random.random() # a randdom no is generated between 0(included) and 1 (excluded)

In [ ]:
lis=[1,2,3,4,5]
lis

In [ ]:
random.shuffle(lis)

In [ ]:
lis


In [ ]:
random.uniform(7,14)

In [ ]:
#random numbers related concepts in numpy
np.array([])

In [ ]:
np.random.random_sample((5,))

In [ ]:
np.random.rand(1)

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randn(2,3)

In [ ]:
arr = np.random.randint(1,5,size=(3,4))

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr.size 

In [ ]:
arr

In [ ]:
#reshaping the array

arr1=arr.reshape(2,6)

In [ ]:
arr1.shape 

In [ ]:
arr1.size

In [ ]:
arr

In [ ]:
arr.size

In [ ]:
#array size will not change , always reshape parameter should be multiplication  of the original array size 

In [ ]:
arr

In [ ]:
arr.size

In [ ]:
arr.reshape(2,6)  ## arr.reshape(2,5) will throw the error because the multiplication is not equal to 12 

In [ ]:
#case when you don't know in reshape what would be column count 
# give any negative value as the column count 
arr.reshape(4,-1)

In [ ]:
arr.reshape(2,-1)

In [ ]:
arr.reshape(2,-100)

In [ ]:
arr1 = arr.reshape(-1,3)#you know column count but no row count 

In [ ]:
arr1.size

In [ ]:
arr.reshape(12,1)

In [ ]:
arr.reshape(12,1).base #to see the original array

In [ ]:
arr.reshape(2,2,3)  # means that two row and three column repeated three times 

In [ ]:
arr.reshape(1,2,2,3).ndim

In [ ]:
arr.reshape(4,3,1) #3 rows 1 column repeated 4 times in the third dimension

In [ ]:
#conditions on array

arr1 = np.random.randint(1,10,(5,6))

arr1.shape

In [ ]:
arr1.shape

In [ ]:
arr1.ndim

In [ ]:
arr1.size 

In [ ]:
arr1 > 3

In [ ]:
arr1

In [ ]:
arr1[arr1>3]

In [ ]:
arr1[arr1<3]

In [ ]:
arr1

In [ ]:
arr1[0]

In [ ]:
arr1[1]


In [ ]:
arr1[1][0]

In [ ]:
arr1

In [ ]:
arr1[0:3]  #0th row , 1th row and 2nd row 

In [ ]:
arr1[0:3,[0,2]] #0 th, 1st row and  2nd column


In [ ]:
arr1[0:2,1:3]

In [ ]:
arr1[0:2 , [0,1]]

In [ ]:
arr1[0,[1,3]]

In [ ]:
arr[2:4, [0,3]]

In [ ]:
arr1[2:5]

In [ ]:
arr1[2:5 , 0:2]

In [ ]:
#mathematical opertion of two arrays
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1+arr2   #indexwise element addition 

In [ ]:
arr1-arr2  #inexwise element substraction

In [ ]:
arr1 * arr2 #index wise multiplication 

In [ ]:
arr1,arr2

In [ ]:
arr1/arr2

In [ ]:
arr1 /  0  #in python array  zero division will give error , but in numpy it will give infinite 

In [ ]:
#matric multiplication >> different from index multiplication

arr1 @ arr2  #first way to do matrix multiplication

In [ ]:
np.dot(arr1,arr2) #2nd method to do matrix multiplication

In [ ]:
arr=np.zeros((3,4))

In [ ]:
arr + 5

In [ ]:
arr - 5

In [ ]:
arr

In [ ]:
a= np.array([1,2,3,4])

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
arr + a

In [ ]:
a= np.array([[1,2,3,4]])

In [ ]:
a

In [ ]:
#Transpose

a.T

In [ ]:
arr1

In [ ]:
arr1.T

In [ ]:
np.sqrt(arr1)

In [ ]:
np.log10(arr1)

In [ ]:
np.exp(arr1)

In [ ]:
np.min(arr1)

In [ ]:
np.max(arr1)

In [ ]:
#lecture 3 Numpy 

In [ ]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,2,(3,3))

In [ ]:
arr1

In [ ]:
arr1.flatten() # return a copy of the array  collapsed into one dimension.

In [ ]:
#expand dimension 

arr = np.array([1,2,3,4])
arr

In [ ]:
arr.ndim

In [ ]:
np.expand_dims(arr,axis=0) # increases the dimension by one at provided axis 


In [ ]:
arr.ndim 

In [ ]:
np.expand_dims(arr,axis=1)

In [ ]:
arr

In [ ]:
arr= np.zeros((3,4))

In [ ]:
arr.ndim

In [ ]:
np.expand_dims(arr, axis=0) 

In [ ]:
np.expand_dims(arr,axis=1)

In [ ]:
np.expand_dims(arr, axis=0).ndim

In [ ]:
a= np.array([[1],[2],[3]])

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
np.squeeze(a)  #remove  axes of length one from 'a' 

In [ ]:
a

In [ ]:
np.repeat(a,4)

In [ ]:
arr1

In [ ]:
np.repeat(arr1,2)

In [ ]:
np.repeat(arr1, 2, axis=0)

In [ ]:
np.repeat(arr1,3,axis=0)

In [ ]:
np.repeat(arr1,3,axis=1)

In [ ]:
a

In [ ]:
np.roll(a,-1)

In [ ]:
np.roll(a,-2)

In [ ]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [ ]:
c

In [ ]:
np.roll(c,-2)

In [ ]:
np.roll(c,2)   #here there is only one rolling as their is 2 dimension that outer one will take one and inner onnw will take the other

In [ ]:
np.roll(c,2,axis=0)  #here by providing the axis will result it will rotate as many time as it is passed 

In [ ]:
arr1+arr2 

In [ ]:
arr1-arr2

In [ ]:
arr1 * arr2 

In [ ]:
arr1 > arr2 

In [ ]:
arr1

In [ ]:
~arr1

In [ ]:
#operations on numpy string array

In [ ]:
d=np.array(["pw","skills"])

In [ ]:
d

In [ ]:
np.char.upper(d)

In [ ]:
np.char.capitalize(d)

In [ ]:
#mathematical functions 

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1+arr2

In [ ]:
arr1-arr2

In [ ]:
arr1 * arr2

In [ ]:
arr1 > arr2 

In [ ]:
arr1

In [ ]:
~arr1

In [ ]:
#operation  on numpy string array

In [ ]:
np.array(["pw","skills"])

In [ ]:
np.char.upper(d)

In [ ]:
np.char.capitalize(d)

In [ ]:
#mathematical function

In [ ]:
arr1

In [ ]:
np.sin(arr1)

In [ ]:
np.cos(arr1)

In [ ]:
np.tan(arr1)

In [ ]:
np.log10(arr1)

In [346]:
np.exp(arr1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [347]:
np.power(arr1, 3)

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [348]:
np.mean(arr1)

np.float64(3.5)

In [349]:
np.max(arr1)

np.int64(6)

In [350]:
np.min(arr1)

np.int64(1)

In [351]:
np.std(arr1)

np.float64(1.707825127659933)

In [352]:
np.var(arr1)

np.float64(2.9166666666666665)

In [353]:
arr1-arr2

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
np.subtract(arr1, arr2 )

In [ ]:
arr1*arr2

In [ ]:
np.multiply(arr1,arr2 )

In [ ]:
np.mod(arr1,arr2)

In [ ]:
np.sqrt(arr1) 

In [ ]:
#sort search
e = np.array([5,6,1,2])

In [ ]:
e

In [ ]:
np.sort(e)

In [ ]:
f= np.array([5,199,200,6,7,8])

In [ ]:
f

In [ ]:
np.sort(f)

In [ ]:
np.searchsorted(f,170) #find indices where the elements should be inserted to maintain order 

In [ ]:
arr1

In [ ]:
f= np.array([5,199,200,6,7,0,0,0,8])

In [ ]:
f

In [ ]:
np.count_nonzero(f)

In [ ]:
f[f>0]

In [ ]:
np.where(f>0)

In [ ]:
np.extract(f>0,f) 

In [ ]:
f.byteswap()


In [ ]:
#matrix >> 2d  array we can explicitly work with the matrix 

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

In [ ]:
nm.ones((3,4))

In [ ]:
#numpy linear algebra 

arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1 @ arr2  # matrix multiplication

In [ ]:
#determinant of the matrix 
np.linalg.det(arr1)

In [ ]:
np.linalg.inv(arr1)

In [ ]:
#solving of linear equation in there  variable / two varaible using determinant 

In [ ]:
a= np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [ ]:
a

In [ ]:
b=np.array([16,8,0])

In [ ]:
b  # values at rhs side of the equation 


In [ ]:
np.linalg.solve(a,b)  